# Generated by Django 4.0.3 on 2022-04-02 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_utc', models.DateTimeField(auto_now_add=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('SAVINGS_ACCOUNT', 'Savings Account'), ('CREDIT_ACCOUNT', 'Credit Account'), ('UNDEFINED_ACCOUNT_TYPE', 'Undefined Account type')], default='UNDEFINED_ACCOUNT_TYPE', max_length=255)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_utc', models.DateTimeField(auto_now_add=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True)),
                ('change_amount', models.DecimalField(decimal_places=8, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('UNDEFINED_TRANSACTION_TYPE', 'Undefined Transaction type')], default='UNDEFINED_TRANSACTION_TYPE', max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
