# Generated by Django 4.0.3 on 2022-03-25 18:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_utc', models.DateTimeField(auto_now_add=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileExtendedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_utc', models.DateTimeField(auto_now_add=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('RM', 'Relational Manager'), ('CLIENT', 'Client'), ('UNDEFINED_ROLE', 'Undefined role')], default='UNDEFINED_ROLE', max_length=255)),
                ('nickname', models.CharField(blank=True, default='', max_length=255)),
                ('address_0', models.CharField(default='', max_length=255)),
                ('address_1', models.CharField(default='', max_length=255)),
                ('cell_number', models.CharField(blank=True, default='', max_length=255)),
                ('personal_website', models.CharField(blank=True, default='', max_length=255)),
                ('managing_rm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileBasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_utc', models.DateTimeField(auto_now_add=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True)),
                ('middle_name', models.CharField(blank=True, default='', max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDEFINED_GENDER', 'Undefined')], default='UNDEFINED_GENDER', max_length=255)),
                ('date_of_birth', models.DateField(default=datetime.date(2000, 1, 1))),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Users.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
